config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :exported_issue_data
  resources :account_configurations

  post 'import' => 'issues#import'
  get 'export' => 'issues#export'
  get 'download' => 'issues#download'

  get 'settings' => 'account_configurations#edit'
  get 'authorize' => 'account_configurations#authorize'
  get 'callback' => 'account_configurations#callback'
  post 'update' => 'account_configurations#update'
  

  root 'issues#index'

end

app/models/account_configuration.rb
class AccountConfiguration < ActiveRecord::Base
  serialize :github, Hash
  serialize :gitlab, Hash

  def github_token
    github[:token]
  end

  def github_user_name
    github[:user]
  end

  def github_repository
    github[:repo]
  end

  def gitlab_endpoint
    gitlab[:endpoint]
  end

  def gitlab_private_token
    gitlab[:private_token]
  end

  def gitlab_project_id
    gitlab[:project_id]
  end

end

app/models/exported_issue_data.rb
class ExportedIssueData < ActiveRecord::Base
  serialize :github_labels, Array
  serialize :gitlab_labels, Array
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  default_scope { order('updated_at DESC') } 

end

app/controllers/account_configurations_controller.rb
class AccountConfigurationsController < ApplicationController

  END_POINT = "https://gitlab.com/api/v3"

  # Updates GitLab Settings and Notification email.
  def edit
    @github = scoper.github
    @gitlab = scoper.gitlab
    @notification_email = scoper.notification_email
  end

  def update
    gitlab = gitlab_auth_data
    if scoper.update_attributes(:gitlab => gitlab, :notification_email => params[:notification_email])
      flash[:notice] = "Settings updated successfully."
    else
      flash[:error] = "There was a problem updating the settings."
    end
    redirect_to settings_path
  end

  # Establishes connection with GitHub, authorizes the connection and updates settings.
  def authorize
    github = Github.new client_id: params[:client_id], client_secret: params[:client_secret]
    scoper.update_attributes(:github => github_auth_data)
    
    address = github.authorize_url redirect_uri: host+'/callback', scope: 'repo'
    redirect_to address
  end

  def callback
    authorization_code = params[:code]
    github = Github.new client_id: scoper.github[:client_id], 
              client_secret: scoper.github[:client_secret]
    begin
      access_token = github.get_token authorization_code
      data = (scoper.github).merge({:token => access_token.token})
      scoper.update_attributes(:github => data)
      flash[:notice] = "Github settings updated succesfully"
    rescue Exception => e
      scoper.update_attributes(:github => {})
      flash[:error] = "There was a problem updating Github Settings. 
        Please check if your credentials are correct and if redirect URI matches"
    end
    
    redirect_to settings_path
  end

  private
    def github
      @github ||= Github.new client_id: @client_id, client_secret: @client_secret
    end

    def scoper
      AccountConfiguration.first || AccountConfiguration.create
    end

    def github_auth_data
      {
        :client_id => params[:client_id],
        :client_secret => params[:client_secret],
        :user => params[:user],
        :repo => params[:repo]
      }
    end

    def gitlab_auth_data
      {
        :endpoint => END_POINT,
        :private_token => params[:private_token],
        :project_id => params[:project_id]
      }
    end

    def host
      @host ||= request.base_url
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exported_issue_data_controller.rb
class ExportedIssueDataController < ApplicationController
  
  # lists previously exported data 
  def index
    @exported_data = ExportedIssueData.paginate :page => params[:page], :per_page => 30
  end

end

app/controllers/issues_controller.rb
require "import_export_methods.rb"

class IssuesController < ApplicationController
	include ImportExportMethods
	
	skip_before_filter :verify_authenticity_token
	before_filter :check_for_valid_input, :validate_csv, :check_for_import_progress, :only => :import
	before_filter :check_for_export_progress, :only => :export
  before_filter :load_account_configuration

  # Lists all issues that were imported before.
	def index
		@issues = Issue.paginate :page => params[:page], :per_page => 20
		@exported_data_count = ExportedIssueData.all.count
		@last_downloaded = @exported_data_count > 0 ? ExportedIssueData.last.created_at : "-"		
	end

  # Imports issues. 
  # Runs in a background thread. 
  # Sends an email when import is done.
	def import
		Thread.new { 
			import_issues(params[:CSV], params, host) 
		}
		flash[:notice] = %(Import has succesfully started. You will be notified via email to 
      #{@account_configuration.notification_email} when the import is done.)
		redirect_to issues_path
	end

  # Exports issues. 
  # Runs in a background thread. 
  # Sends an email with exported file as attachment, when export is done.
	def export
		if Issue.all.count > 0
			Thread.new { export_issues }
			flash[:notice] = %(Export has succesfully started. The exported issues will be sent as attachment 
        via email to #{@account_configuration.notification_email} when the export is done.)
		else
			flash[:error] = "Sorry, there are no issues to export."
		end

		redirect_to issues_path
	end

  # Downloads exported data in the browser.
	def download
    send_data download_exported_data, :filename => 'issues.csv'
  end

  private
  	def host
  		@host ||= request.base_url
  	end

    # Backend validations for import
  	def check_for_valid_input
  		unless (params[:github] or params[:gitlab])
  			flash[:error] = "Please select one of the checkboxes to import."
  			redirect_to issues_path
  		end
  		unless params[:CSV]
				flash[:error] = "Please choose a CSV file to import."
				redirect_to issues_path
			end
  	end

    # Checks if the given file is a valid CSV file and if it is in the right format.
  	def validate_csv
  		headers = CSV.foreach(params[:CSV].path).first
  		unless headers.include?('Issue: Issue Number')
				flash[:error] = "The format of the CSV file you tried importing is invalid."
				redirect_to issues_path
			end
  	end

    # Not more than one import or export can run in the same time. 
    # Avoids data duplication and faster execution.
  	def check_for_import_progress
  		if AccountConfiguration.first.import_progress
				flash[:error] = "An import is under progress. Please wait.."
				redirect_to issues_path
			end
  	end

  	def check_for_export_progress
  		if AccountConfiguration.first.export_progress
				flash[:error] = "An export is under progress. Please wait.."
				redirect_to issues_path
			end
  	end

    def load_account_configuration
      @account_configuration = AccountConfiguration.first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def formated_date(date)    
    date.to_datetime.strftime('%b %d, %Y')
  end
end

app/views/account_configurations/edit.html.erb
<div class="clearfix container row-fluid">
  <div id="issue-content">
    
    <div class="left-content pull-left">
      <% flash.each do |key, value| %>
        <div class="alert <%= key %>">
          <%= value %><a class="close" data-dismiss="alert" href="#">&times;</a>
        </div>
      <% end %>

      <div class="section">
        <h4>GitHub Settings</h4>
        <%= form_tag({action: :authorize}, method: :get) do %>

          <div class="form-control">
            <label>Client ID</label>
            <%= text_field_tag :client_id, @github[:client_id], { :class => "span7", :required => true } %>
          </div>

          <div class="form-control">
            <label>Client Secret</label>
            <%= password_field_tag :client_secret, @github[:client_secret], { :class => "span7",:required => true } %>
          </div>
          <div class="form-control">
            <label>GitHub username</label>
            <%= text_field_tag :user, @github[:user], { :class => "span7", :placeholder => "Example: halbcoder",:required => true } %>
          </div>

          <div class="form-control">
            <label>Repository ID</label>
            <%= text_field_tag :repo, @github[:repo], { :class => "span7", :placeholder => "Example: tc-app",:required => true } %>
          </div>

          <div class="form-control"><br>
            <%= submit_tag 'Update', :class => 'btn' %>
          </div>
        <% end %>
      </div>

      <div class="section">
        <h4>GitLab Settings</h4>
        <%= form_tag({action: :update}) do %>

          <div class="form-control">
            <label>Endpoint</label>
            <%= text_field_tag :endpoint, @gitlab[:endpoint], { :class => "span7", :required => true, :disabled => true } %>
          </div>

          <div class="form-control">
            <label>Private token</label>
            <%= password_field_tag :private_token, @gitlab[:private_token], { :class => "span7", :required => true } %>
          </div>

          <div class="form-control">
            <label>Project ID</label>
            <%= text_field_tag :project_id, @gitlab[:project_id], { :class => "span7",:required => true, :placeholder => "Your GitLab Project ID" } %>
          </div>

          <div class="form-control"><br>
            <%= submit_tag 'Update', :class => 'btn' %>
          </div>
        </div>

        <div class="notif">
          <h4>Send import/export notifications to</h4>
        
          <div class="form-control"><br>
            <%= email_field_tag :notification_email, @notification_email, { :class => "span7", :required => true, :placeholder => "Example: halbcoder@gmail.com" } %>
          </div>

          <div class="form-control">
            <%= submit_tag 'Update', :class => 'btn' %>
          </div>
        <% end %>
        </div>
      
      
    </div>  
    <div class="sidebar pull-right">
      <div>

      </div>
    </div>  
  </div>
</div>

app/views/exported_issue_data/index.html.erb
  <div id="issue-content">
    <div class="left-content export_list_table">
      <% flash.each do |key, value| %>
        <div class="alert <%= key %>">
          <%= value %><a class="close" data-dismiss="alert" href="#">&times;</a>
        </div>
      <% end %>
      <h4>Exported Issues</h4>
      <% if @exported_data.count > 0 %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th width="">CMC Issue ID</th>
              <th width="">GitLab Issue ID</th>
              <th width="">GitLab Title</th>
              <th width="">GitLab Status</th>
              <th width="">GitLab Labels</th>
              <th width="">GitLab Milestones</th>
              <th width="">GitLab last updated</th>
              <th width="">GitHub Issue ID</th>
              <th width="">GitHub Title</th>
              <th width="">GitHub Status</th>
              <th width="">GitHub Labels</th>
              <th width="">GitHub Milestones</th>
              <th width="">GitHub last updated</th>
            </tr>
          </thead>
            <% @exported_data.each do |issue| %>
              <tr>
                <td> <%= issue.cmc_id %></td> 
                <td> <%= issue.gitlab_id %></td>
                <td> <%= issue.gitlab_title %></td>
                <td> <%= issue.gitlab_status %></td>
                <td> <%= issue.gitlab_labels.to_a.to_sentence %></td>
                <td> <%= issue.gitlab_milestones %></td>
                <td> <%= issue.gitlab_last_updated %></td>
                <td> <%= issue.github_id %></td>
                <td> <%= issue.github_title %></td>
                <td> <%= issue.github_status %></td>
                <td> <%= issue.github_labels.to_a.to_sentence %></td>
                <td> <%= issue.github_milestones %></td>
                <td> <%= issue.github_last_updated %></td>
              </tr> 
            <% end %>
        </table>
      <% else %>
        <p>No issues exported so far.</p>
      <% end %>
      <div class = "pull-right">
          <%= will_paginate @exported_data %> 
        </div>
    </div>
  </div>

app/views/issues/index.html.erb
<div class="clearfix container row-fluid">
  <div id="issue-content">
    
    <div class="left-content pull-left">
      <% flash.each do |key, value| %>
        <div class="alert <%= key %>">
          <%= value %><a class="close" data-dismiss="alert" href="#">&times;</a>
        </div>
      <% end %>
      
      <% if @account_configuration.notification_email.blank? %>
        <div class="alert">
          Please set your notification email in the <%= link_to 'Settings', settings_path %> page. Or else you will not receive email notifcations when import or export completes.
        </div>
      <% end %>

      <h4>Uploaded Issues</h4>
      <% if @issues.count > 0 %>
        <table class="table table-striped table-hover" id="issue_list_table">
          <thead>
            <tr>
              <th width="20%">CMC Issue ID</th>
              <th width="20%">GitLab Issue ID</th>
              <th width="20%">GitHub Issue ID</th>
              <th width="20%">Uploaded at</th>
            </tr>
          </thead>
            <% @issues.each do |issue| %>
              <tr>
                <td> <%= issue.cmc_id %></td> 
                <td> <%= issue.gitlab_id || "-" %></td>
                <td> <%= issue.github_id || "-" %></td>
                <td> <%= issue.created_at.strftime('%b %d, %Y') %></td>
              </tr> 
            <% end %>
        </table>
      <% else %>
        <p>There are no issues imported to GitLab or GitHub before.</p>
      <% end %>
        <%= will_paginate @issues %> 
    </div>
    
    <div class="sidebar pull-right" rel="sticky">
      <div id="import-section" class="sidebar-section">
        <h4 class="logo">Import</h4>
          <%= form_tag({action: :import}, multipart: true) do %>
            <% if @issues.count > 0 %>
              <div class="alert span11">
                <%= @issues.count %> issues imported so far.
              </div>
            <% end %>

            <div class="form-control">
              <label>Check the boxes to which the issues are to be imported.</label>
              <label class="pull-left"><%= check_box_tag 'github', 1, true %> GitHub</label>
              <label class=""><%= check_box_tag 'gitlab', 1, true %> GitLab</label>
            </div>

            <div class="form-control">
              <label>Choose a csv file</label>
              <%= file_field_tag 'CSV', accept: 'text/csv', :required => true %><br>
            </div>

            <div class="form-control">
              <%= submit_tag 'Import', :class => 'btn' %>
            </div>  
          <% end %>
      </div>

      <div id="export-section" class="sidebar-section">
        <h4 class="logo">Export</h4>
          
          <%= form_tag({action: :export}, method: 'get') do %>
            <% if @exported_data_count > 0 %>
              <div class="alert span11">
                <%= @exported_data_count %> issues were last exported on <%= formated_date(@last_downloaded) %>. You can <%= link_to "view", exported_issue_data_path %> or
                <%= link_to "download", download_path %> the exported data.
              </div>
            <% end %>
            <div class="form-control">
              <label>Generate a CSV of all available issues with latest updates and send it via email.</label>
              <div class="form-control">
                <%= submit_tag 'Export', :class => 'btn' %>
              </div>  
            </div>
          <% end %>          
      </div>
    </div>
  </div>

</div>

app/views/layouts/_header.html.erb
<header>
  <div class="clearfix container row-fluid">
    <h1 class="logo">GitLab/GitHub Issue uploading tool</h1>    
  

  <div class="span5 pull-right">
      <ul class="pull-right"> 
        <li><%= link_to("Issues", issues_path) %></li>
        <li><%= link_to("Settings", settings_path) %></li>
      </ul>
  </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Issue uploading tool</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => "layouts/header" %>
    
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>